interface University {
  name: string;
  alpha_two_code: string;
  country: string;
  web_pages: string[];
  "state-province": string | null;
  domains: string[];
}

interface CountryData {
  [key: string]: University[];
}

let data: CountryData = {
  pakistan: [
    {
      name: "Information Technology University, Lahore",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["https://itu.edu.pk/"],
      "state-province": "Punjab",
      domains: ["itu.edu.pk"],
    },
    {
      name: "Abasyn University Peshawar",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.abasyn.edu.pk/"],
      "state-province": "Khyber Pakhtunkhwa",
      domains: ["abasyn.edu.pk"],
    },
    {
      name: "Allama Iqbal Open University",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.aiou.edu.pk/"],
      "state-province": null,
      domains: ["aiou.edu.pk"],
    },
    {
      name: "Azad Jammu and Kashmir University",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.ajku.edu.pk/"],
      "state-province": null,
      domains: ["ajku.edu.pk"],
    },
    {
      name: "Aga Khan University",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.aku.edu/"],
      "state-province": "Sindh",
      domains: ["aku.edu"],
    },
    {
      name: "Jamia Al Dirasat Ul Islami Karachi",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.aldirasat.edu.pk/"],
      "state-province": "Sindh",
      domains: ["aldirasat.edu.pk"],
    },
    {
      name: "Al-Khair University",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.alkhair.edu.pk/"],
      "state-province": null,
      domains: ["alkhair.edu.pk"],
    },
    {
      name: "Ahmed Medical Institute",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.ami.edu.pk/"],
      "state-province": "Khyber Pakhtunkhwa",
      domains: ["ami.edu.pk"],
    },
    {
      name: "Air University",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.au.edu.pk/"],
      "state-province": "Panjab",
      domains: ["au.edu.pk"],
    },
    {
      name: "The University of Agriculture, Peshawar",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.aup.edu.pk/"],
      "state-province": "Khyber Pakhtunkhwa",
      domains: ["aup.edu.pk"],
    },
    {
      name: "Bahria University",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.bahria.edu.pk/"],
      "state-province": "Panjab",
      domains: ["bahria.edu.pk"],
    },
    {
      name: "Barani Institute of Information Technology",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["http://www.biit.edu.pk/"],
      "state-province": "Panjab",
      domains: ["biit.edu.pk"],
    },
    {
      name: "University of central punjab",
      alpha_two_code: "PK",
      country: "Pakistan",
      web_pages: ["https://ucp.edu.pk/"],
      "state-province": "Panjab",
      domains: ["biit.edu.pk"],
    },
  ],
  france: [
    {
      name: "Ecole Centrale de Lille",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://www.ec-lille.fr/"],
      "state-province": null,
      domains: ["ec-lille.fr"],
    },
    {
      name: "Ecole Centrale de Lyon",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://www.ec-lyon.fr/"],
      "state-province": null,
      domains: ["ec-lyon.fr"],
    },
    {
      name: "Ecole Centrale de Nantes",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://www.ec-nantes.fr/"],
      "state-province": null,
      domains: ["ec-nantes.fr"],
    },
    {
      name: "Ecole Centrale de Marseille",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["https://www.centrale-marseille.fr/"],
      "state-province": null,
      domains: ["centrale-marseille.fr"],
    },
    {
      name: "IDRAC (Institut de recherche en action commerciale)",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://www.ecoles-idrac.com/"],
      "state-province": null,
      domains: ["ecoles-idrac.com"],
    },
    {
      name: "Ecole des Hautes Etudes Commerciales du Nord",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://edu.edhec.com/"],
      "state-province": null,
      domains: ["edu.edhec.com"],
    },
    {
      name: "Ecole pour les Etudes et la Recherche en Informatique et Electronique",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://www.eerie.fr/"],
      "state-province": null,
      domains: ["eerie.fr"],
    },
    {
      name: "Ecole Française de Papeterie et des Industries Graphiques",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://www.efpg.inpg.fr/"],
      "state-province": null,
      domains: ["efpg.inpg.fr"],
    },
    {
      name: "Ecole Française d'Electronique et d'Informatique",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://www.efrei.fr/"],
      "state-province": null,
      domains: ["efrei.fr"],
    },
    {
      name: "Ecole des Ingénieurs de la Ville de Paris",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://www.eivp-paris.fr/"],
      "state-province": null,
      domains: ["eivp-paris.fr"],
    },
    {
      name: "European Management Center Paris",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://www.emc-campus.com/"],
      "state-province": null,
      domains: ["emc-campus.com"],
    },
    {
      name: "Ecole Supérieure de Commerce de Lyon",
      alpha_two_code: "FR",
      country: "France",
      web_pages: ["http://www.em-lyon.com/"],
      "state-province": null,
      domains: ["em-lyon.com"],
    },
  ],
  germany: [
    {
      name: "AKAD Hochschulen für Berufstätige, Fachhochschule Leipzig",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://www.akad.de/"],
      "state-province": null,
      domains: ["akad.de"],
    },
    {
      name: "Alice-Salomon-Fachhochschule für Sozialarbeit und Sozialpädagogik Berlin",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://www.asfh-berlin.de/"],
      "state-province": null,
      domains: ["asfh-berlin.de"],
    },
    {
      name: "Augustana Hochschule Neuendettelsau",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://www.augustana.de/"],
      "state-province": null,
      domains: ["augustana.de"],
    },
    {
      name: "Kirchliche Hochschule Bethel",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://www.bethel.de/kiho/"],
      "state-province": null,
      domains: ["bethel.de"],
    },
    {
      name: "BiTS - Business and Information Technology School gGmbH",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://www.bits-iserlohn.de/"],
      "state-province": null,
      domains: ["bits-iserlohn.de"],
    },
    {
      name: "Cologne Business School",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://www.cbs.de/"],
      "state-province": null,
      domains: ["cbs.de"],
    },
    {
      name: "CODE University of Applied Sciences Berlin",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://code.berlin/"],
      "state-province": null,
      domains: ["code.berlin"],
    },
    {
      name: "Deutsche Hochschule für Verwaltungswissenschaften Speyer",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://www.dhv-speyer.de/"],
      "state-province": null,
      domains: ["dhv-speyer.de"],
    },
    {
      name: "DIPLOMA-Fachhochschule Ölsnitz/Vogtland",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://www.diploma.de/"],
      "state-province": null,
      domains: ["diploma.de"],
    },
    {
      name: "Deutsche Sporthochschule Köln",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://www.dshs-koeln.de/"],
      "state-province": null,
      domains: ["dshs-koeln.de"],
    },
    {
      name: "E.A.P. Europäische Wirtschaftshochschule Berlin",
      alpha_two_code: "DE",
      country: "Germany",
      web_pages: ["http://www.eap.net/"],
      "state-province": null,
      domains: ["eap.net"],
    },
  ],
  italy: [
    {
      name: "Pontificia Università S. Tommaso",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.angelicum.org/"],
      "state-province": null,
      domains: ["angelicum.org"],
    },
    {
      name: "Pontificio Ateneo Antonianum",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.antonianum.ofm.org/"],
      "state-province": null,
      domains: ["antonianum.ofm.org"],
    },
    {
      name: "University of Modena",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.casa.unimo.it/"],
      "state-province": null,
      domains: ["casa.unimo.it"],
    },
    {
      name: "Abdus Salam international centre for theoretical physics",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.ictp.trieste.it/"],
      "state-province": null,
      domains: ["ictp.trieste.it"],
    },
    {
      name: "Institute for Advanced Studies Lucca",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.imtlucca.it/"],
      "state-province": null,
      domains: ["imtlucca.it"],
    },
    {
      name: "University Institute of Architecture Venice",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.iuav.unive.it/"],
      "state-province": null,
      domains: ["iuav.unive.it"],
    },
    {
      name: "European University Institute",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.iue.it/"],
      "state-province": null,
      domains: ["iue.it"],
    },
    {
      name: "University Institute of Modern Languages",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.iulm.it/"],
      "state-province": null,
      domains: ["iulm.it"],
    },
    {
      name: "Dutch University Institute for Art History (DUIA)",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.iuoart.org/"],
      "state-province": null,
      domains: ["iuoart.org"],
    },
    {
      name: "University Institute of Oriental Studies",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.iuo.it/"],
      "state-province": null,
      domains: ["iuo.it"],
    },
    {
      name: "Istituto Universitario di Studi Superiori",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.iusspavia.it/"],
      "state-province": null,
      domains: ["iusspavia.it"],
    },
    {
      name: "Johns Hopkins University, SAIS Bologna Center",
      alpha_two_code: "IT",
      country: "Italy",
      web_pages: ["http://www.jhubc.it/"],
      "state-province": null,
      domains: ["jhubc.it"],
    },
  ],
  uk: [
    {
      name: "West Herts College",
      alpha_two_code: "GB",
      web_pages: ["https://westherts.ac.uk"],
      country: "United Kingdom",
      domains: ["student.westherts.ac.uk", "westherts.ac.uk"],
      "state-province": null,
    },
    {
      name: "Royal Holloway University of London",
      alpha_two_code: "GB",
      web_pages: ["https://rhul.ac.uk"],
      country: "United Kingdom",
      domains: ["rhul.ac.uk"],
      "state-province": null,
    },
    {
      name: "United Medical and Dental Schools, University of London",
      alpha_two_code: "GB",
      country: "United Kingdom",
      web_pages: ["http://www.umds.ac.uk/"],
      "state-province": null,
      domains: ["umds.ac.uk"],
    },
    {
      name: "University of North London",
      alpha_two_code: "GB",
      country: "United Kingdom",
      web_pages: ["http://www.unl.ac.uk/"],
      "state-province": null,
      domains: ["unl.ac.uk"],
    },
    {
      name: "Middlesbrough College",
      alpha_two_code: "GB",
      country: "United Kingdom",
      web_pages: ["https://www.mbro.ac.uk/"],
      "state-province": null,
      domains: ["middlesbro.ac.uk", "mbro.ac.uk"],
    },
    {
      name: "St Mary's University",
      alpha_two_code: "GB",
      country: "United Kingdom",
      web_pages: ["https://www.stmarys.ac.uk/home.aspx"],
      "state-province": null,
      domains: ["stmarys.ac.uk"],
    },
    {
      name: "Leeds Trinity University",
      alpha_two_code: "GB",
      country: "United Kingdom",
      web_pages: ["https://www.leedstrinity.ac.uk/"],
      "state-province": null,
      domains: ["leedstrinity.ac.uk"],
    },
    {
      name: "East Coast College",
      alpha_two_code: "GB",
      country: "United Kingdom",
      web_pages: ["https://www.eastcoast.ac.uk/"],
      "state-province": null,
      domains: ["eastcoast.ac.uk"],
    },
    {
      name: "Swansea University",
      alpha_two_code: "GB",
      country: "United Kingdom",
      web_pages: ["https://www.swansea.ac.uk/"],
      "state-province": null,
      domains: ["swansea.ac.uk"],
    },
    {
      name: "York St. John University",
      alpha_two_code: "GB",
      country: "United Kingdom",
      web_pages: ["https://www.yorksj.ac.uk/"],
      "state-province": null,
      domains: ["yorksj.ac.uk"],
    },
    {
      name: "Cardiff and Vale College",
      alpha_two_code: "GB",
      country: "United Kingdom",
      web_pages: ["https://cavc.ac.uk/"],
      "state-province": null,
      domains: ["cavc.ac.uk"],
    },
    {
      name: "Wakefield College",
      alpha_two_code: "GB",
      web_pages: ["https://wakefield.ac.uk"],
      country: "United Kingdom",
      domains: ["wakefield.ac.uk"],
      "state-province": null,
    },
  ],
};
export default data;
